package openstack

import "github.com/cloudskiff/driftctl/pkg/resource"

func InitResourcesMetadata(resourceSchemaRepository resource.SchemaRepositoryInterface) {
	initOpenStackComputeKeypairV2MetaData(resourceSchemaRepository)
	initOpenStackComputeFlavorV2MetaData(resourceSchemaRepository)
	initOpenStackComputeSecgroupV2MetaData(resourceSchemaRepository)
	initOpenStackComputeInstanceV2MetaData(resourceSchemaRepository)
	initOpenStackBlockstorageVolumeV2MetaData(resourceSchemaRepository)
	initOpenStackNetworkingPortV2MetaData(resourceSchemaRepository)
	initOpenStackNetworkingFloatingipV2MetaData(resourceSchemaRepository)
	initOpenStackNetworkingNetworkV2MetaData(resourceSchemaRepository)
	initOpenStackNetworkingRouterInterfaceV2MetaData(resourceSchemaRepository)
	initOpenStackNetworkingRouterV2MetaData(resourceSchemaRepository)
	initOpenStackNetworkingSecgroupRuleV2MetaData(resourceSchemaRepository)
	initOpenStackNetworkingSecgroupV2MetaData(resourceSchemaRepository)
	initOpenStackNetworkingSubnetV2MetaData(resourceSchemaRepository)
	initOpenStackDNSRecordsetV2MetaData(resourceSchemaRepository)
	initOpenStackDNSZoneV2MetaData(resourceSchemaRepository)
	initOpenStackImagesImageV2MetaData(resourceSchemaRepository)
	initOpenStackComputeVolumeAttachV2MetaData(resourceSchemaRepository)
	initOpenStackComputeInterfaceAttachV2MetaData(resourceSchemaRepository)
}
