package openstack

import "github.com/cloudskiff/driftctl/pkg/resource"

func InitResourcesMetadata(resourceSchemaRepository resource.SchemaRepositoryInterface) {
	initOpenStackComputeKeypairV2MetaData(resourceSchemaRepository)
	initOpenStackComputeFlavorV2MetaData(resourceSchemaRepository)
	initOpenStackComputeSecgroupV2MetaData(resourceSchemaRepository)
	initOpenStackComputeInstanceV2MetaData(resourceSchemaRepository)
	initOpenStackBlockstorageVolumeV2MetaData(resourceSchemaRepository)
}
